# ACI playbook - Create Production Tenant

- name: Create Production Tenant
  hosts: '*apic1'
  connection: local
  gather_facts: no
  
  vars:
    aci_login: &aci_login
        host: "{{ ansible_host }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password | default(omit) }}"
        private_key: "{{ aci_private_key | default(omit) }}"
        certificate_name: "{{ aci_certificate_name | default(omit) }}"
        validate_certs: "{{ aci_validate_certs }}"
        annotation: "orchestrator:ansible"
    shared_l3out_name: L3OUT_CORE

  tasks:
    - name: Add Production Tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        tenant: production_tn
        description: Production tenant
        state: present
        output_path: dryrun_data.json

    # Networking

    - name: Add Production VRF
      cisco.aci.aci_vrf:
        <<: *aci_login
        vrf: prod_vrf
        tenant: production_tn
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present
        output_path: dryrun_data.json

    - name: Add 192.168.210.0/24 bridge domain
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.210.0_24_bd
        vrf: prod_vrf
        l2_unknown_unicast: proxy
        arp_flooding: yes
        enable_routing: yes
        state: present
        output_path: dryrun_data.json

    - name: Add 192.168.210.0/24 bridge domain subnet
      cisco.aci.aci_bd_subnet:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.210.0_24_bd
        gateway: 192.168.210.1
        mask: 24
        scope:  [public, shared]
        state: present
        output_path: dryrun_data.json
    
    - name: Bind 192.168.210.0/24 bridge domain to Core L3Out
      cisco.aci.aci_bd_to_l3out:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.210.0_24_bd
        l3out: "{{ shared_l3out_name }}"
        state: present
        output_path: dryrun_data.json
    
    - name: Add 192.168.211.0/24 bridge domain
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.211.0_24_bd
        vrf: prod_vrf
        l2_unknown_unicast: proxy
        arp_flooding: yes
        enable_routing: yes
        state: present
        output_path: dryrun_data.json

    - name: Add 192.168.211.0/24 bridge domain subnet
      cisco.aci.aci_bd_subnet:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.211.0_24_bd
        gateway: 192.168.211.1
        mask: 24
        scope:  [public, shared]
    
    - name: Bind 192.168.211.0/24 bridge domain to Core L3Out
      cisco.aci.aci_bd_to_l3out:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.211.0_24_bd
        l3out: "{{ shared_l3out_name }}"

    - name: Add 192.168.212.0/24 bridge domain
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.212.0_24_bd
        vrf: prod_vrf
        l2_unknown_unicast: proxy
        arp_flooding: yes
        enable_routing: yes
        state: present
        output_path: dryrun_data.json

    - name: Add 192.168.212.0/24 bridge domain subnet
      cisco.aci.aci_bd_subnet:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.212.0_24_bd
        gateway: 192.168.212.1
        mask: 24
        scope:  [public, shared]
        state: present
        output_path: dryrun_data.json
    
    - name: Bind 192.168.212.0/24 bridge domain to Core L3Out
      cisco.aci.aci_bd_to_l3out:
        <<: *aci_login
        tenant: production_tn
        bd: 192.168.212.0_24_bd
        l3out: "{{ shared_l3out_name }}"
        state: present
        output_path: dryrun_data.json
